STM_IP_address: 169.254.34.144
last_MWlist: C:/Users/scharfetter_admin/Documents/MW_Aufzeichnungen/COHIRADIA/Softwareentwicklung/COHIWizard_2023/sources/MWLIST_Volltabelle.xlsx
last_path: G:/Datenfiles/Barteczek_RCaroline_Easter2024
recording_path: C:/Users/scharfetter_admin/Downloads
