STM_IP_address: 169.254.34.144
last_MWlist: C:/Users/scharfetter_admin/Documents/MW_Aufzeichnungen/COHIRADIA/Softwareentwicklung/SDR_Postprocessor/MWLIST_Volltabelle.xlsx
last_path: C:/Users/scharfetter_admin/Documents/MW_Aufzeichnungen/COHIRADIA/Softwareentwicklung/IASA_Gallenmiller_Projekt/modulated_output
