STM_IP_address: 169.254.34.144
ffmpeg_path: C:\Users\scharfetter_admin\Documents\MW_Aufzeichnungen\COHIRADIA\Softwareentwicklung\COHIWizard_2023\sources\ffmpeg-7.1-essentials_build\bin
last_audiosource_path: C:/Users/scharfetter_admin/Eigene Musik/Camerata Vocal Group/Just
last_path: C:/Users/scharfetter_admin/Documents/MW_Aufzeichnungen/COHIRADIA/Softwareentwicklung/COHIWizard_2023/sources/out
recording_path: C:\Users\scharfetter_admin\Documents\MW_Aufzeichnungen\COHIRADIA\Softwareentwicklung\COHIWizard_2023\sources\out
rootpath: C:\Users\scharfetter_admin\Documents\MW_Aufzeichnungen\COHIRADIA\Softwareentwicklung\COHIWizard_2023\sources
